# Generated by Django 3.2.5 on 2021-12-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0023_auto_20211218_1949'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_animatedpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('animated', models.BooleanField(default=True, verbose_name='Animated')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ColumnPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_columnpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('xs', models.PositiveSmallIntegerField(blank=True, help_text='<767px', null=True, verbose_name='X-Small')),
                ('sm', models.PositiveSmallIntegerField(blank=True, help_text='≥768px', null=True, verbose_name='Small')),
                ('md', models.PositiveSmallIntegerField(blank=True, help_text='≥992px', null=True, verbose_name='Medium')),
                ('lg', models.PositiveSmallIntegerField(blank=True, help_text='≥1200px', null=True, verbose_name='Large')),
                ('offset_xs', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset x-small')),
                ('offset_sm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset small')),
                ('offset_md', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset medium')),
                ('offset_lg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset large')),
                ('hide_xs', models.BooleanField(default=False, verbose_name='Hide on x-small devices')),
                ('hide_sm', models.BooleanField(default=False, verbose_name='Hide on small devices')),
                ('hide_md', models.BooleanField(default=False, verbose_name='Hide on medium devices')),
                ('hide_lg', models.BooleanField(default=False, verbose_name='Hide on large devices')),
                ('gray_bg_color', models.BooleanField(default=False, verbose_name='Background Color - Gray')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=55, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_en', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_es', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=35, verbose_name='Phone')),
                ('phone_en', models.CharField(max_length=35, null=True, verbose_name='Phone')),
                ('phone_es', models.CharField(max_length=35, null=True, verbose_name='Phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('message_es', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Us Offer',
                'verbose_name_plural': 'Contact Us Offers',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_googlemappluginmodel', serialize=False, to='cms.cmsplugin')),
                ('src', models.CharField(help_text='Just copy src from iframe and paste here', max_length=500, verbose_name='Src')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeaderSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_headersectionpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Title')),
                ('bg_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RowPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_rowpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('text_align', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=15, null=True, verbose_name='Text align')),
                ('horizontal_padding', models.CharField(blank=True, max_length=25, null=True, verbose_name='Horizontal padding')),
                ('vertical_padding', models.CharField(blank=True, max_length=25, null=True, verbose_name='Vertical padding')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SpacePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_spacepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('space_height', models.PositiveSmallIntegerField(verbose_name='Space height')),
                ('xs', models.PositiveSmallIntegerField(blank=True, help_text='<767px', null=True, verbose_name='Space height on x-small devices')),
                ('sm', models.PositiveSmallIntegerField(blank=True, help_text='≥768px', null=True, verbose_name='Space height on small devices')),
                ('md', models.PositiveSmallIntegerField(blank=True, help_text='≥992px', null=True, verbose_name='Space height on medium devices')),
                ('lg', models.PositiveSmallIntegerField(blank=True, help_text='≥1200px', null=True, verbose_name='Space height on large devices')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TitlePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_titlepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=155, null=True, verbose_name='Subtitle')),
                ('with_bg_image', models.BooleanField(default=False, verbose_name='With bg image?')),
                ('text_align', models.CharField(choices=[('L', 'Left'), ('C', 'Center')], default='L', max_length=1, verbose_name='Text align')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image in row')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_imagepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
                ('object_fit_cover', models.BooleanField(default=False, help_text='Useful when image stretched and you want to fix by cutting the edge', verbose_name='Cover image')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeHeaderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_homeheaderpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeHeaderAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Text')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='core.homeheaderpluginmodel')),
                ('simple_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.headersectionpluginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Answer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': "FAQ's",
            },
        ),
        migrations.CreateModel(
            name='CounterItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_counteritempluginmodel', serialize=False, to='cms.cmsplugin')),
                ('prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Suffix')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Value')),
                ('name', models.CharField(max_length=255)),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AsideNavigationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'en'), ('es', 'es'), ('ru', 'ru')], max_length=25, verbose_name='Language')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsBlockPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_aboutusblockpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=155, null=True, verbose_name='Subtitle')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Content')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
