# Generated by Django 3.2.5 on 2021-08-01 15:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug услуги')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('cost_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Название к цене')),
                ('teaser_description', ckeditor.fields.RichTextField(blank=True, help_text='Текст который будет описывать услугу на других страницах', null=True, verbose_name='Интро текст')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('what_we_offer_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание блока "плюсы услуг"')),
                ('what_we_offer_video_url', models.URLField(blank=True, max_length=155, null=True, verbose_name='URL видео блока возле цены')),
                ('header_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение шапки')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to=settings.FILER_IMAGE_MODEL, verbose_name='Иконка услуги')),
                ('what_we_offer_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='what_we_offer_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение блока "плюсы услуг"')),
            ],
        ),
    ]
