# Generated by Django 3.2.5 on 2021-12-16 10:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBlockPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_aboutusblockpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=155, null=True, verbose_name='Subtitle')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ColumnPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_columnpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('xs', models.PositiveSmallIntegerField(blank=True, help_text='<767px', null=True, verbose_name='X-Small')),
                ('sm', models.PositiveSmallIntegerField(blank=True, help_text='≥768px', null=True, verbose_name='Small')),
                ('md', models.PositiveSmallIntegerField(blank=True, help_text='≥992px', null=True, verbose_name='Medium')),
                ('lg', models.PositiveSmallIntegerField(blank=True, help_text='≥1200px', null=True, verbose_name='Large')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=35, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='CounterItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_counteritempluginmodel', serialize=False, to='cms.cmsplugin')),
                ('prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Suffix')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Value')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_googlemappluginmodel', serialize=False, to='cms.cmsplugin')),
                ('src', models.CharField(help_text='Just copy src from iframe and paste here', max_length=500, verbose_name='src')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=155, verbose_name='Название страницы')),
                ('page_slug', models.SlugField(blank=True, null=True, verbose_name='Slug страницы')),
                ('main_page', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('meta_description', models.CharField(blank=True, max_length=455, null=True, verbose_name='Мета описание')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SpacePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_spacepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('space_height', models.PositiveSmallIntegerField(verbose_name='Space height')),
                ('xs', models.PositiveSmallIntegerField(blank=True, help_text='<767px', null=True, verbose_name='Space height on x-small devices')),
                ('sm', models.PositiveSmallIntegerField(blank=True, help_text='≥768px', null=True, verbose_name='Space height on small devices')),
                ('md', models.PositiveSmallIntegerField(blank=True, help_text='≥992px', null=True, verbose_name='Space height on medium devices')),
                ('lg', models.PositiveSmallIntegerField(blank=True, help_text='≥1200px', null=True, verbose_name='Space height on large devices')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TitlePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_titlepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=155, null=True, verbose_name='Subtitle')),
                ('with_bg_image', models.BooleanField(default=False, verbose_name='With bg image?')),
                ('text_align', models.CharField(choices=[('L', 'Left'), ('C', 'Center')], default='L', max_length=1, verbose_name='Text align')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image in row')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_imagepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
                ('object_fit_cover', models.BooleanField(default=False, help_text='Useful when image stretched and you want to fix by cutting the edge', verbose_name='Cover image')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeaderSectionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_headersectionpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Title')),
                ('bg_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
