# Generated by Django 3.2.5 on 2021-08-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
