# Generated by Django 3.2.5 on 2021-12-16 13:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0023_auto_20211216_1029'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeaderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_homeheaderpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeHeaderAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.homeheaderpluginmodel')),
            ],
        ),
    ]
