# Generated by Django 3.2.5 on 2021-12-16 14:19

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeheaderaddressmodel_homeheaderpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusblockpluginmodel',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='homeheaderaddressmodel',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Текст'),
        ),
    ]
