# Generated by Django 3.2.5 on 2021-11-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_galleryvideo'),
        ('core', '0004_contactusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
