# Generated by Django 3.2.5 on 2021-12-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        ('core', '0004_auto_20211216_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_rowpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('horizontal_padding', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horizontal padding')),
                ('vertical_padding', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vertical padding')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
