# Generated by Django 3.2.5 on 2021-12-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rowpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowpluginmodel',
            name='horizontal_padding',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Horizontal padding'),
        ),
        migrations.AlterField(
            model_name='rowpluginmodel',
            name='vertical_padding',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Vertical padding'),
        ),
    ]
