# Generated by Django 3.2.5 on 2021-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=155, verbose_name='Название страницы')),
                ('page_slug', models.SlugField(verbose_name='Slug страницы')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('meta_description', models.CharField(blank=True, max_length=455, null=True, verbose_name='Мета описание')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
