# Generated by Django 3.2.5 on 2021-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug страницы'),
        ),
    ]
