# Generated by Django 3.2.5 on 2021-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211216_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnpluginmodel',
            name='hide_lg',
            field=models.BooleanField(default=False, verbose_name='Hide on large devices'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='hide_md',
            field=models.BooleanField(default=False, verbose_name='Hide on medium devices'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='hide_sm',
            field=models.BooleanField(default=False, verbose_name='Hide on small devices'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='hide_xs',
            field=models.BooleanField(default=False, verbose_name='Hide on x-small devices'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='offset_lg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset large'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='offset_md',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset medium'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='offset_sm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset small'),
        ),
        migrations.AddField(
            model_name='columnpluginmodel',
            name='offset_xs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset x-small'),
        ),
    ]
