# Generated by Django 3.2.5 on 2021-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_page_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main_page',
            field=models.BooleanField(default=False),
        ),
    ]
