# Generated by Django 3.2.5 on 2021-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211216_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowpluginmodel',
            name='text_align',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], max_length=1, null=True, verbose_name='Text align'),
        ),
    ]
