# Generated by Django 3.2.5 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rowpluginmodel_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowpluginmodel',
            name='text_align',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=15, null=True, verbose_name='Text align'),
        ),
    ]
