# Generated by Django 3.2.5 on 2021-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rowpluginmodel_text_align'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'Contact Us Offer', 'verbose_name_plural': 'Contact Us Offers'},
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='email_es',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='message_es',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='name_es',
            field=models.CharField(max_length=55, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='phone_en',
            field=models.CharField(max_length=35, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='phone_es',
            field=models.CharField(max_length=35, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='phone',
            field=models.CharField(max_length=35, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='googlemappluginmodel',
            name='src',
            field=models.CharField(help_text='Just copy src from iframe and paste here', max_length=500, verbose_name='Src'),
        ),
    ]
