# Generated by Django 3.2.5 on 2021-12-17 13:04

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        ('core', '0011_auto_20211217_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedTextPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_animatedtextpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Text')),
                ('animated', models.BooleanField(default=False, verbose_name='Aminated')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='homeheaderaddressmodel',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Text'),
        ),
    ]
