# Generated by Django 3.2.5 on 2021-12-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        ('core', '0012_auto_20211217_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_animatedpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('animated', models.BooleanField(default=False, verbose_name='Aminated')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='AnimatedTextPluginModel',
        ),
    ]
