# Generated by Django 3.2.5 on 2021-12-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatedpluginmodel',
            name='animated',
            field=models.BooleanField(default=True, verbose_name='Animated'),
        ),
    ]
