# Generated by Django 3.2.5 on 2021-12-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_animatedpluginmodel_animated'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnpluginmodel',
            name='gray_bg_color',
            field=models.BooleanField(default=False, verbose_name='Background Color - Gray'),
        ),
    ]
