# Generated by Django 3.2.5 on 2021-12-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0016_auto_20211218_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsideNavigationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_asidenavigationpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AsideNavigationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('navigation_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='core.asidenavigationpluginmodel')),
            ],
        ),
    ]
