# Generated by Django 3.2.5 on 2021-12-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_asidenavigationflag_asidenavigationpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asidenavigationflag',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('es', 'es'), ('ru', 'ru')], default='en', max_length=25, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
