# Generated by Django 3.2.5 on 2021-12-18 19:49

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0023_auto_20211218_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555, verbose_name='Name')),
                ('name_en', models.CharField(max_length=555, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=555, null=True, verbose_name='Name')),
                ('custom_slug', models.BooleanField(default=False, verbose_name='Custom Slug')),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(blank=True, max_length=555, null=True, unique=True, verbose_name='Slug')),
                ('slug_es', models.SlugField(blank=True, max_length=555, null=True, unique=True, verbose_name='Slug')),
                ('cost', models.PositiveIntegerField(verbose_name='Cost')),
                ('cost_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name')),
                ('cost_name_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name')),
                ('cost_name_es', models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duration')),
                ('teaser_description', models.CharField(blank=True, help_text='Text which is seen from other pages (Teaser)', max_length=575, null=True, verbose_name='Intro Text')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('description_en', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('description_es', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('video_url', models.CharField(blank=True, max_length=575, null=True, verbose_name='Video Url')),
                ('h1_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Title')),
                ('h1_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Title')),
                ('h1_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Title')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo Page Title')),
                ('page_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo Page Title')),
                ('page_title_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo Page Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_description_es', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', slotname='content', to='cms.placeholder')),
                ('description_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Description Image')),
                ('extra_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', slotname='extra', to='cms.placeholder')),
                ('header', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', slotname='header', to='cms.placeholder')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to=settings.FILER_IMAGE_MODEL, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceRowPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='services_servicerowpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('display_type', models.CharField(choices=[('S', 'Simple'), ('B', 'Blocks')], max_length=1, verbose_name='Display type')),
                ('fetch_from_db', models.BooleanField(default=True, verbose_name='Fetch from db?')),
                ('max_count', models.PositiveSmallIntegerField(blank=True, default=6, help_text='How much services to display', null=True, verbose_name='Max')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServicePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='services_servicepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Service Gallery Video',
                'verbose_name_plural': 'Service Gallery Videos',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='ExtraPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Cost')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
