# Generated by Django 3.2 on 2021-05-06 20:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Короткое название услуги', max_length=75, verbose_name='Название')),
                ('title', models.CharField(help_text='Подброное название услуги', max_length=155, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст отображающийся в блоке "Benefits of service"', verbose_name='Польза услуги')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('short_description', models.CharField(max_length=75, verbose_name='Короткое описание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Опция услуги',
                'verbose_name_plural': 'Опции услуг',
            },
        ),
    ]
