# Generated by Django 3.2.5 on 2021-08-01 15:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='cost_name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Название к цене'),
        ),
        migrations.AddField(
            model_name='service',
            name='header_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение шапки'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to=settings.FILER_IMAGE_MODEL, verbose_name='Иконка услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='teaser_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Текст который будет описывать услугу на других страницах', null=True, verbose_name='Интро текст'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_we_offer_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание блока "плюсы услуг"'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_we_offer_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='what_we_offer_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение блока "плюсы услуг"'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_we_offer_video_url',
            field=models.URLField(blank=True, max_length=155, null=True, verbose_name='URL видео блока возле цены'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug услуги'),
        ),
        migrations.DeleteModel(
            name='ServiceOption',
        ),
    ]
