# Generated by Django 3.2.5 on 2021-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210801_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность процедуры'),
        ),
    ]
