# Generated by Django 3.2.5 on 2021-12-16 14:16

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211216_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_es',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='teaser_description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Текст который будет описывать услугу на других страницах', null=True, verbose_name='Интро текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='teaser_description_en',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Текст который будет описывать услугу на других страницах', null=True, verbose_name='Интро текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='teaser_description_es',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Текст который будет описывать услугу на других страницах', null=True, verbose_name='Интро текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='what_we_offer_description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание блока "плюсы услуг"'),
        ),
        migrations.AlterField(
            model_name='service',
            name='what_we_offer_description_en',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание блока "плюсы услуг"'),
        ),
        migrations.AlterField(
            model_name='service',
            name='what_we_offer_description_es',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание блока "плюсы услуг"'),
        ),
    ]
