# Generated by Django 3.2.5 on 2021-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo заголовок страницы'),
        ),
    ]
