# Generated by Django 3.2.5 on 2021-12-17 13:48

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        ('services', '0006_auto_20211217_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', slotname='content', to='cms.placeholder'),
        ),
        migrations.AlterField(
            model_name='service',
            name='header',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', slotname='header', to='cms.placeholder'),
        ),
    ]
