# Generated by Django 3.2.5 on 2021-11-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_galleryvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение для галереи', 'verbose_name_plural': 'Изображения для галереи'},
        ),
        migrations.AlterModelOptions(
            name='galleryvideo',
            options={'verbose_name': 'Видео для галереи', 'verbose_name_plural': 'Видео для галереи'},
        ),
    ]
