# Generated by Django 3.2.5 on 2021-12-17 21:16

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        ('services', '0007_auto_20211217_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', slotname='extra', to='cms.placeholder'),
        ),
    ]
