# Generated by Django 3.2.5 on 2021-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_extra_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155, verbose_name='Name')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Cost')),
            ],
        ),
    ]
