# Generated by Django 3.2.5 on 2021-12-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_extraprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraprice',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='extraprice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
    ]
