# Generated by Django 3.2.5 on 2021-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20211218_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='teaser_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='teaser_description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='teaser_description_es',
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_name_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_name_es',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Cost Name'),
        ),
    ]
