# Generated by Django 3.2.5 on 2021-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20211118_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=555, verbose_name='Название услуги'),
        ),
    ]
