# Generated by Django 3.2.5 on 2021-12-18 07:00

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('services', '0015_auto_20211218_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Description Image'),
        ),
    ]
