# Generated by Django 3.2.5 on 2021-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.CharField(blank=True, max_length=575, null=True, verbose_name='Video'),
        ),
    ]
