# Generated by Django 3.2.5 on 2021-12-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='video',
            new_name='video_url',
        ),
    ]
