# Generated by Django 3.2.5 on 2021-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_rename_video_service_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_slug',
            field=models.BooleanField(default=False, verbose_name='Custom Slug'),
        ),
    ]
