# Generated by Django 3.2.5 on 2021-12-16 10:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211216_1029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('h1_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Заголовок')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo заголовок страницы')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержимое')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('h1_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Заголовок')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo заголовок страницы')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета описание')),
                ('author', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogRecentItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='blog_blogrecentitempluginmodel', serialize=False, to='cms.cmsplugin')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
