# Generated by Django 3.2.5 on 2021-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seo заголовок страницы'),
        ),
    ]
