# Generated by Django 3.2 on 2021-05-06 20:26

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='Скидочная цена')),
                ('slug', models.SlugField(blank=True, max_length=155, null=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('page_title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Page title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('main_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
