# Generated by Django 3.2.5 on 2021-12-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Basket Open Date')),
                ('ordered_date', models.DateTimeField(verbose_name='Basket Order Date')),
                ('basket_changed_date', models.DateField(blank=True, null=True, verbose_name='Basket Changes Date')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordered')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Cost')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='Discount')),
                ('slug', models.SlugField(blank=True, max_length=155, null=True, verbose_name='Slug')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Description')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('page_title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Page title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('main_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('related_products', models.ManyToManyField(related_name='_shop_product_related_products_+', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Product Count')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Ordered')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('which_basket', models.ManyToManyField(blank=True, to='shop.Basket', verbose_name='Basket')),
            ],
            options={
                'verbose_name': 'Basket Product',
                'verbose_name_plural': 'Basket Products',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='shop.BasketProduct', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
