# Generated by Django 3.2.5 on 2021-12-16 14:19

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Описание'),
        ),
    ]
