# Generated by Django 3.2.5 on 2021-08-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Проект из Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
