# Generated by Django 3.2.5 on 2021-12-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Portfolio Project', 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
    ]
