# Generated by Django 3.2.5 on 2021-11-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='alt_text',
        ),
    ]
