# Generated by Django 3.2.5 on 2021-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_type',
            field=models.BooleanField(default=True, verbose_name='Отзыв - фотография?'),
        ),
    ]
