# Generated by Django 3.2.5 on 2021-11-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
